### PR TITLE
HA Core 2025.1 Deprecated Constants update

### PR DESCRIPTION
**Pull request by craibo**
Updates to resolve:

HVAC_MODE_OFF was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
SUPPORT_TARGET_TEMPERATURE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
SUPPORT_FAN_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
SUPPORT_SWING_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues
SUPPORT_PRESET_MODE was used from panasonic_cc, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.PRESET_MODE instead, please create a bug report at https://github.com/sockless-coding/panasonic_cc/issues

### CODE REVIEW

**Comment by craibo** [comment]
Relates to https://github.com/sockless-coding/panasonic_cc/issues/164

**Review by codyc1515 — APPROVED** [review]

**Review by killer0071234 — APPROVED** [review]
LGTM

**Comment by Ricks88** [comment]
It says merged in master, but we can not choose versions anymore, only the latest. (at least i can not install any other version than the latest release)

**Comment by jpakanen2** [comment]
When this change contained release will be published?

**Comment by sockless-coding** [comment]
Before or during summer depends on when I have time to finish "the move" of the update calls to a DataUpdateCoordinator.
2025.1 won't release until Jan 2025

**Pull request merged**
