### PR TITLE
Only set-up the Nanoe switch if the device supports it

### PR DESCRIPTION
**Pull request by codyc1515**

### CODE REVIEW

**Comment by sockless-coding** [comment]
Removing it is not a good option, this will cause a broken sensor to appear. A better way is to change the registry to disabled & hidden depending on if the sensor is available.

**Comment by codyc1515** [comment]
That wasn’t my experience with this. Instead, it just doesn’t add the entity.

**Comment by sockless-coding** [comment]
It will look like this for everyone that doesn't have nanoe support and have had the integration:
image
image

**Comment by sockless-coding** [comment]
Setting the registry to disabled & hidden would result in the following:
image
image
The reason I didn't implemented this for EcoNavi was I wanted to have some feedback if it was working or not. And it requires the implementation of a EntityDescription

**Comment by codyc1515** [comment]
> It will look like this for everyone that doesn't have nanoe support and have had the integration: image image

This makes sense to me as it is indeed no longer provided by the integration.

**Pull request closed without merging**
