### PR TITLE
Set the correct device and state classes for the energy sensors

### PR DESCRIPTION
**Pull request by hsmade**
So they will be recognised as such.

### CODE REVIEW

**Comment by purcell-lab** [comment]
Fixes #49

**Comment by Ricks88** [comment]
Is this available now? Still cant find a fix for HA energy tab

**Comment by sockless-coding** [comment]
> Is this available now? Still cant find a fix for HA energy tab

The daily energy sensor should work as a consumption device. 
If it's not working correctly, you might want to check under Developer Tools - Statistics and see if it's marked with any issues.

**Comment by Ricks88** [comment]
> > Is this available now? Still cant find a fix for HA energy tab
> 
> The daily energy sensor should work as a consumption device. If it's not working correctly, you might want to check under Developer Tools - Statistics and see if it's marked with any issues.

Thanks! seems to work.

I had this still in my customizations:
sensor.panasonic_vloermodel_daily_energy:
  state_class: total_increasing
  device_class: energy
  
  Can it be removed now?

**Comment by codyc1515** [comment]
Any update for this @sockless-coding ? I could take over the integration if you no longer wish to support it.

**Comment by codyc1515** [comment]
Can this be merged now? I think the consts may need updating.

**Pull request closed without merging**
