### PR TITLE
Generate API key

### LINKED ISSUE #331: Precondition Failed
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.10.4

### Describe the issue

Aircon dashboard went unavailable ~30 minutes ago. Reviewed logs, found 'Precondition failed'. Logging into the Panasonic App works without issue and the Aircon can still be controlled via the app, just not HA.

image

image

### Error/Debug Logs

```text
Logger: custom_components.panasonic_cc.coordinator
Source: custom_components/panasonic_cc/coordinator.py:86
integration: Panasonic Comfort Cloud (documentation, issues)
First occurred: 11:37:36 (56 occurrences)
Last logged: 12:05:05

Error fetching device data from API: (get_status: Expected status code 200, received: 412: { "code":41201, "message":"Precondition Failed" }
Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/coordinator.py", line 86, in _fetch_device_data
    if await self._api_client.try_update_device(self._device):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 178, in try_update_device
    json_response = await self._get_device_status(device.info)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/apiclient.py", line 169, in _get_device_status
    json_response = await self.execute_get(self._get_device_status_now_url(device_info.guid), "get_status", 200)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/pcomfortcloud/panasonicsession.py", line 145, in execute_get
    await check_response(response, function_description, expected_status_code)
  File "/config/custom_components/panasonic_cc/pcomfortcloud/helpers.py", line 32, in check_response
    raise exceptions.ResponseError(
custom_components.panasonic_cc.pcomfortcloud.exceptions.ResponseError: (get_status: Expected status code 200, received: 412: {
  "code":41201,
  "message":"Precondition Failed"
}
```

### PR DESCRIPTION
**Pull request by hrrrsn**
Fixes #331 , #333, #334

### CODE REVIEW

**Comment by sockless-coding** [comment]
I'm still getting the precondition failed

**Comment by hrrrsn** [comment]
Hmm. I only had my units installed 3 days ago (post-API change - disappointing) so I'm using a fresh install/login if that makes a difference - they're working correctly, I have no errors.

One part I'm not entirely clear on is the `cfc` injection. The header you posted in the issue is missing it, but every request I've generated from iOS has it present.

**Comment by sockless-coding** [comment]
The android version has the cfc as well, could be some issue with something not getting encoded correctly maybe special chars in the token

**Comment by sockless-coding** [comment]
I did a replay of using the method:
Expected: `02230b977cfc86179cac19e48bd387062ed43222ded416377c87e0806ced8385206`
Got: `7940423d8cfc47d6907152d7c445b5df85efd8629495fe95d060e172e0f787f866b`

**Comment by hrrrsn** [comment]
Hmm, my Home Assistant container is running in UTC - does that change anything?

**Comment by sockless-coding** [comment]
Yes, that's the issue converting the time to UTC before turning it into a timestamp fixes the issue

**Comment by sockless-coding** [comment]
I moved the utc conversion, since the timestamp sent by the client is the local time

**Comment by sockless-coding** [comment]
just to make it look like their requests

**Comment by sockless-coding** [comment]
@hrrrsn great job!

**Comment by raczgy** [comment]
It works, thank you! I'm not sure who I should buy the coffee for. :)

**Comment by Garagoos** [comment]
Absolutely fantastic work - thank you very much

I would like to buy more than one coffee - but I don't have a credit card

Do you have a Paypal account? I think this work should be supported and honored!

**Comment by codyc1515** [comment]
Would it not now be prudent to reduce the polling frequency or even just make that a toggle?

**Comment by sockless-coding** [comment]
@codyc1515 there are already options to set the polling rate separate for data and energy and a button to request new data.

**Comment by codyc1515** [comment]
I would also really enjoy seeing a write up or any pointers on how you did this. I’d like to do the same for BYD.

**Comment by sockless-coding** [comment]
@codyc1515 depending on how much of the code is located in a native lib, it might not be worth the effort. But you can always throw the lib at https://dogbolt.org/ and see what comes out.

**Pull request merged**
