### PR TITLE
Create low temperature mode

### LINKED ISSUE #20: Exposing built-in Summerhouse mode
Hi, 
Thank you for this great integration.
I have a unit CS-HZ25UKE, which has a "summer house mode". This essentially allows to have low temperature maintained  in summerhouses to avoid mold/frost during the winter.

There are two summer house mode selected under "device list":

"+8-15°C HEAT" allows to choose any target temperature between + 8 and +15°C. Forces fan mode automatically as "HIGH".
"+8 or 10°C HEAT"  allows to choose any target temperature between + 8 or+10°C. Forces fan mode automatically as "HIGH".
I do no know the point of the second one, and the first one is the only one that makes sense.
See Screenshots of the app attached.

_Would it be possible to expose this mode as part of the integration and have it available as an operation mode?_

Note: It is possible to "imitate" this by calling the services "climate.set_temperature" to 8 and "climate.set_hvac_mode" to "heat" and climate.set_fan_mode to "high" which is what I do as part of an automation when temperature inside get too low.

Screenshot_20201221-092918_Comfort Cloud
Screenshot_20201221-092910_Comfort Cloud
Screenshot_20201221-093050_Comfort Cloud

### PR DESCRIPTION
**Pull request by karlrank**
Some (many) panasonic heat pumps allow for a freezing protection or low temperature 8-10C mode.

This PR adds this mode optionally, but keeps the default behaviour.

Fixes #20, #85 and #92

### CODE REVIEW

**Comment by codyc1515** [comment]
This looks like it has the commits from #155 in it too. Could you please re-base it?

**Comment by karlrank** [comment]
Right you are @codyc1515 ! Changed it to only have the relevant commit.

**Comment by sockless-coding** [comment]
Adding the "Summer House" / "Freeze protection" mode isn't as easy as just allowing lower temperature.
Depending on what the API return on the `summerHouse` property, this is done differently.
I haven't had time to look in depth how the different `summerHouse` types work, but from what I gather from the App there are 3 different types `1`, `2` and `3`. And they all work slightly different.

**Comment by karlrank** [comment]
Fair enough, but do we have proper documentation do know how exactly summerHouse modes actually work? If there was such a thing I'd of course be happy to implement all of the modes "properly", but for now I have at least anecdotal evidence that this setting works exactly as intended for me, and therefore probably would also help some other people all while almost certainly doing no harm.

My `summerHouse` mode is `2`. Would you like the option of enabling low-temperature mode automatically only if summerHouse mode was 2 more for example?

Full data dump from my pump for reference:
```json
{
    "uiFlg": false,
    "groupCount": 1,
    "groupList":
    [
        {
            "groupId": 1234567,
            "groupName": "XXXXXX",
            "pairingList":
            [],
            "deviceList":
            [
                {
                    "deviceGuid": "CS-NZ25YKE+XXXXXXX",
                    "deviceType": "3",
                    "deviceName": "Summerhouse heat pump",
                    "permission": 3,
                    "temperatureUnit": 0,
                    "summerHouse": 2,
                    "nanoeStandAlone": true,
                    "autoMode": true,
                    "modeAvlList":
                    {
                        "autoMode": 1
                    },
                    "parameters":
                    {
                        "operate": 1,
                        "operationMode": 3,
                        "temperatureSet": 8,
                        "fanSpeed": 5,
                        "fanAutoMode": 1,
                        "airSwingLR": 2,
                        "airSwingUD": 1,
                        "ecoFunctionData": 0,
                        "ecoMode": 0,
                        "ecoNavi": 0,
                        "nanoe": 1,
                        "iAuto": 0,
                        "airDirection": 1,
                        "lastSettingMode": 0
                    },
                    "deviceModuleNumber": "CS-NZ25YKE",
                    "deviceHashGuid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                    "modelVersion": 1,
                    "coordinableFlg": true,
                    "pairedFlg": false
                }
            ]
        }
    ]
}
```

**Comment by sockless-coding** [comment]
This has been added as a preset

**Pull request closed without merging**
